### ISSUE TITLE
Add a workflow file for GitHub Actions

### ISSUE THREAD

**Issue by yutaro-sakamoto** [opensourcecobol/gnucobol-osscons-patch#10]
I will create a workflow file for GitHub Actions.
It should be useful in all development situations.

**Comment by yutaro-sakamoto** [comment]
This issue overlaps with #9

**Comment by GitMensch** [comment]
This is now implemented and likely should be closed. I do suggest to update the definitions first, using https://github.com/OCamlPro/gnucobol/tree/gcos4gnucobol-3.x/.github/workflows - this includes everything in here but VBISAM (which you want to test either additional or instead of BDB).
